apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimation-π_2vCPUs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estimation-π_2vCPUs
  template:
    metadata:
      labels:
        app: estimation-π_2vCPUs
    spec:
      containers:
      - name: estimation-π_2vCPUs
        image: dockerhub_user/estimation-π_2vCPUs
        env:
        - name: NUM_THREADS
          value: "2"
        volumeMounts:
        - name: results
          mountPath: /workspace/results
      volumes:
      - name: results
        hostPath:
          path: /home/worker1/results_est_π
          type: DirectoryOrCreate